name: Build and Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-15]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: "3.20.x"

      - name: Install Dependencies (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config git ninja-build clang perl golang
          sudo apt-get remove -y libssl-dev

      - name: Install Dependencies (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install openssl@3 pkg-config golang

      - name: Cache Build Directory
        uses: actions/cache@v3
        with:
          path: |
            build
          key: ${{ runner.os }}-cmake-${{ hashFiles('**/*.c', '**/*.h', 'CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-cmake-

      - name: Build and Test
        run: |
          chmod +x ./build.sh
          ./build.sh
